import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Sidebar } from "@/components/sidebar";
import { Button } from "@/components/ui/button";
import { Menu, Search, Settings } from "lucide-react";
import { ScrollArea, ScrollBar } from "@/components/ui/scroll-area";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next.js Movies App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="app-container">
          <Sidebar />
          <main className="lg:p-4 h-dvh overflow-hidden">
            <div className="lg:border lg:rounded-lg flex flex-col h-full ">
              <div className="flex border-b p-4">
                <div className="lg:hidden">
                <Button size="icon" variant={`outline`}>
                    <Menu size={16} />
                  </Button>
                </div>
                <div className="ml-auto flex space-x-2">
                  <Button size="icon" variant={`outline`}>
                    <Search size={16} />
                  </Button>
                  <Button size="icon" variant={`outline`}>
                    <Settings size={16} />
                  </Button>
                </div>
              </div>
              <div className="overflow-y-auto">
            {children}
            </div>
            </div>
          </main>
        </div>
      </body>
    </html>
  );
}
